### ISSUE TITLE
Is there any chance we can add the speaker info fields to the session submission form?

### ISSUE THREAD

**Issue by rootwork** [DevSignerCon/DevSignerCon-2015#96]
The workflow for adding a session with speakers still doesn't make a lot of sense to me, and I'm having trouble figuring out how to describe it to people and where to even send them first.

So they're on the session submission form. They get all the way down to the bottom and want to add themselves and another person. They discover first they have to get that person to register (bottleneck). Then they have to go to their user page, and edit it, and add their speaker information. And have the other speaker do that too. And then go back to the session submission page and re-enter all the other information.

The alternative is dumping them directly onto their user edit page upon logging in, in the hopes that adding a bunch of bio stuff won't distract them from submitting a session, which is what we want them to do and what we desperately need. (And of course if there's another speaker they still have to wait while they register.)

If we're pulling in the speaker name via reference, is there any chance we can pull in the other fields so they can fill them out right there on the session form?

**Comment by rootwork** [comment]
OK, so since the "public" speaker profile fields were on the registration form already and since Gonz says we don't need any of the sponsors to register, I updated some of the language and added the speaking experience field. So now when people aren't logged in and try to submit a session, it'll take them to login/registration, where they'll add that info as they sign up.

Still doesn't address the multiple-speaker thing, but I'm guessing that's not really fixable this year.

**Comment by Greg-Boggs** [comment]
The workflow is:
1. click link to register to submit a session which takes you to user register where you fill out speaker information.
2. Once that's complete you get the dashboard which gives you a call to action to submit your first session
3. Once you click that CTA, you can fill in your session details. 

The workflow isn't great. The purpose for it is so that you don't have to reassign authors to accepted sessions after they are submitted. In an ideal world, we could combine the user form with the entity form on a single form so that you register and submit a session at the same time.

For multiple speakers, each extra speaker has to register and fill out their profile before they can be added to a session.

**Comment by jmallison** [comment]
I want to add that maybe there should be some text on the speaker portion of the form explaining that they can edit the session after it's accepted to add additional speakers... They don't have to have them register -before- they submit the form... they can always add them later.

**Comment by Greg-Boggs** [comment]
The reason the user fields are on the user rather than the session is so that when 1 person submits 2 sessions, their same profile is attached to multiple sessions and if you change a speaker on a session, the session's speaker information updates completely from that one change.

**Comment by rootwork** [comment]
Ah OK. Thanks for that clarification.

I'll add to the help text as you suggest.

**Comment by rootwork** [comment]
I've added the text per Jay's suggestion. I think this can be closed for this year.
